In [2]:
# Theoretical Questions:

In [3]:
#  1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

In [4]:
# numpy is written in c language which is one of the fastest language,numpy provide numpy array,which is way faster than python data structure like list and tuple.
# operation on numpy is faster than on python built in data structure

In [5]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [6]:
# Both np.mean() and np.average() are used to compute the average of an array,np.mean() calculates the arithmetic mean of the elements along a specified axis
# while np.average() calculates the weighted average of the elements.

In [7]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [8]:
# 1D Array Reversal
# Using Slicing, reverse a 1D array by using slicing with a step of -1.

In [9]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)


[5 4 3 2 1]


In [10]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)
reversed_rows_ud = np.flipud(arr_2d)
print(reversed_rows_ud)
reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)
reversed_columns_lr = np.fliplr(arr_2d)
print(reversed_columns_lr)


[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [11]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4])
data_type = arr.dtype
print(data_type)


int64


In [15]:
# Different data types consume different amounts of memory. For example, an int64 takes 8 bytes, while an int32 takes 4 bytes.
# Choosing the appropriate data type can significantly reduce memory usage, especially for large datasets.
# Using smaller data types (like np.int8 or np.float32) when possible can save memory without sacrificing performance.
# The performance of operations can be affected by data types. For instance, operations on float64 are generally slower than on float32 due to the increased
# complexity of handling larger data types.

In [16]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [17]:
# numpy ndarrays is a data structure or a container to store data of same data type.In list we can store different data types,but array store onlt homogeneous data types.
# we know that same data type have continuous memory location so the calculation on array is much faster than the list

In [18]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [19]:
# Contiguous Memory Allocation: NumPy arrays store data in contiguous blocks of memory, which reduces overhead and improves cache performance.
#  Python lists, on the other hand, are arrays of pointers to objects, leading to increased memory overhead.
#  Fixed Data Types: NumPy arrays have a fixed data type, which allows for optimized memory storage. Python lists can hold mixed types, but this
#  flexibility incurs additional overhead and fragmentation.
#  Vectorized Operations: NumPy supports vectorized operations, which means operations are performed on entire arrays rather than element-by-element.
#  This is implemented in C, allowing for significant speed improvements.
#  Efficient Operations on Arrays of Different Shapes: NumPy allows for broadcasting, which enables operations on arrays of different shapes without
#  needing explicit loops or reshaping, leading to more concise and efficient code.

In [20]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In [22]:
# In NumPy, vstack() and hstack() are used to stack arrays vertically and horizontally, respectively.
# np.vstack Stacks arrays in sequence vertically (row-wise).
# np.hstack() Stacks arrays in sequence horizontally (column-wise).

In [24]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
vstack_result = np.vstack((arr1, arr2))
print(vstack_result)


[[1 2]
 [3 4]
 [5 6]]


In [25]:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5], [6]])
hstack_result = np.hstack((arr3, arr4))
print("Horizontal Stack Result:")
print(hstack_result)


Horizontal Stack Result:
[[1 2 5]
 [3 4 6]]


In [26]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In [28]:
# # In NumPy, fliplr() and flipud() are functions used to flip arrays, but they operate in different orientations:
# flipslr() flips an array from left to right (horizontally).
# flipud() Purpose: Flips an array from up to down (vertically).

In [29]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [30]:
# The np.array_split() function in NumPy is used to split an array into multiple sub-arrays. It is particularly useful when you want to divide an
# array into smaller chunks or sections. Here’s a detailed overview of its functionality and how it handles uneven splits.

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
split_even = np.array_split(arr, 3)
print("Even Split:")
print(split_even)


Even Split:
[array([1, 2]), array([3, 4]), array([5, 6])]


In [33]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [32]:
# Vectorization refers to the practice of performing operations on entire arrays (or large chunks of data) at once, rather than using explicit loops to process
# individual elements. In NumPy, vectorized operations are executed in compiled code (typically in C), which is much faster than Python loops.
# Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes. It automatically expands the smaller array
# across the larger array's dimensions so that they have compatible shapes for element-wise operations.

In [34]:
# Practical Questions:

In [35]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [38]:
import numpy as np
array_3x3 = np.random.randint(1, 101, size=(3, 3))
print(array_3x3)
print("")
transposed_array = np.transpose(array_3x3)
print(transposed_array)


[[17 80 47]
 [76 73 85]
 [68 31 49]]

[[17 76 68]
 [80 73 31]
 [47 85 49]]


In [39]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [40]:
import numpy as np

array_1d = np.arange(10)
print("Original 1D Array:")
print(array_1d)
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(array_2x5)

array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [41]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [42]:
import numpy as np
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


Original 4x4 Array:
[[0.84462298 0.19685857 0.46140264 0.05282745]
 [0.72293366 0.16942596 0.77007215 0.35058328]
 [0.67417595 0.64420035 0.5410381  0.91579487]
 [0.14560988 0.02918296 0.79515888 0.05007278]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.84462298 0.19685857 0.46140264 0.05282745 0.        ]
 [0.         0.72293366 0.16942596 0.77007215 0.35058328 0.        ]
 [0.         0.67417595 0.64420035 0.5410381  0.91579487 0.        ]
 [0.         0.14560988 0.02918296 0.79515888 0.05007278 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [43]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [45]:
import numpy as np
array_integers = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:")
print(array_integers)


Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [46]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [47]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(string_array)
lowercase = np.char.lower(string_array)
titlecase = np.char.title(string_array)
capitalize = np.char.capitalize(string_array)

# Display the results
print("Original Array:")
print(string_array)

print("\nUppercase:")
print(uppercase)

print("\nLowercase:")
print(lowercase)

print("\nTitle Case:")
print(titlecase)

print("\nCapitalized:")
print(capitalize)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


In [48]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [49]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

# Display the result
print("Original Array of Words:")
print(words_array)

print("\nWords with Spaces Between Characters:")
print(spaced_words)


Original Array of Words:
['hello' 'world' 'numpy' 'python']

Words with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


In [50]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [51]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2
print("Element-wise Addition:")
print(addition)

# Perform element-wise subtraction
subtraction = array1 - array2
print("\nElement-wise Subtraction:")
print(subtraction)

# Perform element-wise multiplication
multiplication = array1 * array2
print("\nElement-wise Multiplication:")
print(multiplication)

# Perform element-wise division
division = array1 / array2
print("\nElement-wise Division:")
print(division)


Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [52]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [53]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)
# Alternatively, you can use: diagonal_elements = identity_matrix.diagonal()

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [54]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [55]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)
print("Array of Random Integers:")
print(random_integers)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Array of Random Integers:
[392 843  49 847 656 497 324 716  32 714 167 601 977 712 199 224 179 361
 332 743 861 158 305 186  41  68 626 704 683 672  23 943   0 608 697 357
  10 613 377 296 610 491 459 994 378 265 132 825 812 304   7   7 285 716
 559 864 605 431 751 806 213 637 804 979 891 931 988 735 655 103 436 648
 627 407 116  28 191 198 859 558 823 330 598  65 455 152 323 233 942 172
 443 638 988 266 115 940 490 356 896 369]

Prime Numbers in the Array:
[167, 601, 977, 199, 179, 743, 41, 683, 23, 613, 491, 7, 7, 431, 751, 103, 191, 859, 823, 233, 443]
